"""initial db schema with all models and indexes

Revision ID: 156dc69adc64
Revises: 
Create Date: 2026-07-28 02:07:58.053397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156dc69adc64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('price_inr', sa.Integer(), nullable=True),
    sa.Column('stock_image_urls', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('seller_id', sa.String(length=256), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_platform', 'products', ['platform'], unique=False)
    op.create_index('ix_products_platform_id', 'products', ['platform_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('measurements', sa.Text(), nullable=True),
    sa.Column('style_preferences', sa.Text(), nullable=True),
    sa.Column('skin_tone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_index('ix_users_clerk_id', 'users', ['clerk_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('target_price_inr', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_user_id', 'alerts', ['user_id'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_image_url', sa.Text(), nullable=False),
    sa.Column('stock_match_score', sa.Float(), nullable=False),
    sa.Column('authenticity_score', sa.Float(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('platform_review_id', sa.String(length=256), nullable=True),
    sa.Column('reviewer_text', sa.Text(), nullable=True),
    sa.Column('reviewer_images', sa.Text(), nullable=True),
    sa.Column('stock_match_score', sa.Float(), nullable=True),
    sa.Column('is_flagged_fake', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_product_id', 'reviews', ['product_id'], unique=False)
    op.create_table('wardrobe_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('purchase_price_inr', sa.Integer(), nullable=True),
    sa.Column('times_worn', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wardrobe_items_user_id', 'wardrobe_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wardrobe_items_user_id', table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    op.drop_index('ix_reviews_product_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('confidence_scores')
    op.drop_index('ix_alerts_user_id', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_users_clerk_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_platform_id', table_name='products')
    op.drop_index('ix_products_platform', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
